steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/wave-hris/app:staging-$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/wave-hris/app:staging"
      - "."

  # Push both tags
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "--all-tags"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/wave-hris/app"

  # Deploy to the staging Cloud Run service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - wave-hris-staging
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/wave-hris/app:staging-$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--quiet"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/wave-hris/app:staging-$COMMIT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/wave-hris/app:staging"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
