/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedDtrRouteImport } from './routes/_authenticated/dtr'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminPerformanceAdminRouteImport } from './routes/_authenticated/_admin/performance-admin'
import { Route as AuthenticatedAdminKpiBuilderRouteImport } from './routes/_authenticated/_admin/kpi-builder'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/_admin/employees'
import { Route as AuthenticatedAdminCutoffsRouteImport } from './routes/_authenticated/_admin/cutoffs'
import { Route as AuthenticatedAdminCutoffApprovalRouteImport } from './routes/_authenticated/_admin/cutoff-approval'
import { Route as AuthenticatedAdminCutoffApprovalIdRouteImport } from './routes/_authenticated/_admin/cutoff-approval_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDtrRoute = AuthenticatedDtrRouteImport.update({
  id: '/dtr',
  path: '/dtr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPerformanceAdminRoute =
  AuthenticatedAdminPerformanceAdminRouteImport.update({
    id: '/performance-admin',
    path: '/performance-admin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKpiBuilderRoute =
  AuthenticatedAdminKpiBuilderRouteImport.update({
    id: '/kpi-builder',
    path: '/kpi-builder',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCutoffsRoute =
  AuthenticatedAdminCutoffsRouteImport.update({
    id: '/cutoffs',
    path: '/cutoffs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCutoffApprovalRoute =
  AuthenticatedAdminCutoffApprovalRouteImport.update({
    id: '/cutoff-approval',
    path: '/cutoff-approval',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCutoffApprovalIdRoute =
  AuthenticatedAdminCutoffApprovalIdRouteImport.update({
    id: '/cutoff-approval_/$id',
    path: '/cutoff-approval/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dtr': typeof AuthenticatedDtrRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/cutoff-approval': typeof AuthenticatedAdminCutoffApprovalRoute
  '/cutoffs': typeof AuthenticatedAdminCutoffsRoute
  '/employees': typeof AuthenticatedAdminEmployeesRoute
  '/kpi-builder': typeof AuthenticatedAdminKpiBuilderRoute
  '/performance-admin': typeof AuthenticatedAdminPerformanceAdminRoute
  '/cutoff-approval/$id': typeof AuthenticatedAdminCutoffApprovalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dtr': typeof AuthenticatedDtrRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/cutoff-approval': typeof AuthenticatedAdminCutoffApprovalRoute
  '/cutoffs': typeof AuthenticatedAdminCutoffsRoute
  '/employees': typeof AuthenticatedAdminEmployeesRoute
  '/kpi-builder': typeof AuthenticatedAdminKpiBuilderRoute
  '/performance-admin': typeof AuthenticatedAdminPerformanceAdminRoute
  '/cutoff-approval/$id': typeof AuthenticatedAdminCutoffApprovalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dtr': typeof AuthenticatedDtrRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/_admin/cutoff-approval': typeof AuthenticatedAdminCutoffApprovalRoute
  '/_authenticated/_admin/cutoffs': typeof AuthenticatedAdminCutoffsRoute
  '/_authenticated/_admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/_admin/kpi-builder': typeof AuthenticatedAdminKpiBuilderRoute
  '/_authenticated/_admin/performance-admin': typeof AuthenticatedAdminPerformanceAdminRoute
  '/_authenticated/_admin/cutoff-approval_/$id': typeof AuthenticatedAdminCutoffApprovalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dtr'
    | '/leaves'
    | '/performance'
    | '/cutoff-approval'
    | '/cutoffs'
    | '/employees'
    | '/kpi-builder'
    | '/performance-admin'
    | '/cutoff-approval/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dtr'
    | '/leaves'
    | '/performance'
    | '/cutoff-approval'
    | '/cutoffs'
    | '/employees'
    | '/kpi-builder'
    | '/performance-admin'
    | '/cutoff-approval/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dtr'
    | '/_authenticated/leaves'
    | '/_authenticated/performance'
    | '/_authenticated/_admin/cutoff-approval'
    | '/_authenticated/_admin/cutoffs'
    | '/_authenticated/_admin/employees'
    | '/_authenticated/_admin/kpi-builder'
    | '/_authenticated/_admin/performance-admin'
    | '/_authenticated/_admin/cutoff-approval_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dtr': {
      id: '/_authenticated/dtr'
      path: '/dtr'
      fullPath: '/dtr'
      preLoaderRoute: typeof AuthenticatedDtrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/performance-admin': {
      id: '/_authenticated/_admin/performance-admin'
      path: '/performance-admin'
      fullPath: '/performance-admin'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/kpi-builder': {
      id: '/_authenticated/_admin/kpi-builder'
      path: '/kpi-builder'
      fullPath: '/kpi-builder'
      preLoaderRoute: typeof AuthenticatedAdminKpiBuilderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/employees': {
      id: '/_authenticated/_admin/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/cutoffs': {
      id: '/_authenticated/_admin/cutoffs'
      path: '/cutoffs'
      fullPath: '/cutoffs'
      preLoaderRoute: typeof AuthenticatedAdminCutoffsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/cutoff-approval': {
      id: '/_authenticated/_admin/cutoff-approval'
      path: '/cutoff-approval'
      fullPath: '/cutoff-approval'
      preLoaderRoute: typeof AuthenticatedAdminCutoffApprovalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/cutoff-approval_/$id': {
      id: '/_authenticated/_admin/cutoff-approval_/$id'
      path: '/cutoff-approval/$id'
      fullPath: '/cutoff-approval/$id'
      preLoaderRoute: typeof AuthenticatedAdminCutoffApprovalIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCutoffApprovalRoute: typeof AuthenticatedAdminCutoffApprovalRoute
  AuthenticatedAdminCutoffsRoute: typeof AuthenticatedAdminCutoffsRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminKpiBuilderRoute: typeof AuthenticatedAdminKpiBuilderRoute
  AuthenticatedAdminPerformanceAdminRoute: typeof AuthenticatedAdminPerformanceAdminRoute
  AuthenticatedAdminCutoffApprovalIdRoute: typeof AuthenticatedAdminCutoffApprovalIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCutoffApprovalRoute: AuthenticatedAdminCutoffApprovalRoute,
  AuthenticatedAdminCutoffsRoute: AuthenticatedAdminCutoffsRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminKpiBuilderRoute: AuthenticatedAdminKpiBuilderRoute,
  AuthenticatedAdminPerformanceAdminRoute:
    AuthenticatedAdminPerformanceAdminRoute,
  AuthenticatedAdminCutoffApprovalIdRoute:
    AuthenticatedAdminCutoffApprovalIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDtrRoute: typeof AuthenticatedDtrRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDtrRoute: AuthenticatedDtrRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
